local colors = require('colors').load()

return {
  BufferLineTab = { foreground = colors.fg, background = colors.bg },
  BufferLineTabClose = { foreground = colors.fg, background = colors.bg, bold = true },
  BufferLineTabSelected = {
    foreground = colors.blue,
    background = colors.bg,
    bold = true,
    italic = true,
  },
  BufferLineBackground = { foreground = colors.fg_alt, background = colors.bg },
  BufferLineBufferSelected = {
    foreground = colors.fg,
    background = colors.bg,
    bold = true,
    italic = true,
  },
  BufferLineBufferVisible = { foreground = colors.fg, background = colors.bg },
  BufferLineCloseButton = { foreground = colors.fg_alt, background = colors.bg },
  BufferLineCloseButtonSelected = { foreground = colors.fg, background = colors.bg, bold = true },
  BufferLineCloseButtonVisible = { foreground = colors.fg, background = colors.bg },
  BufferLineModified = { foreground = colors.green, background = colors.bg },
  BufferLineModifiedSelected = { foreground = colors.green, background = colors.bg },
  BufferLineModifiedVisible = { foreground = colors.green, background = colors.bg },
  BufferLineFill = { foreground = colors.blue, background = colors.bg_alt },
  BufferLineIndicatorSelected = { foreground = colors.blue, background = colors.bg },
  BufferLineSeparator = { foreground = colors.base0, background = colors.bg },
  BufferLineSeparatorSelected = { foreground = colors.base0, background = colors.bg },
  BufferLineSeparatorVisible = { foreground = colors.base0, background = colors.bg_alt },
  BufferLinePick = { foreground = colors.fg, background = colors.bg, bold = true },
  BufferLinePickSelected = {
    foreground = colors.blue,
    background = colors.bg,
    bold = true,
    italic = true,
  },
  BufferLinePickVisible = { foreground = colors.fg, background = colors.bg_alt },

  BufferLineDiagnostic = { foreground = colors.fg, background = colors.bg, sp = colors.fg },
  BufferLineDiagnosticSelected = {
    foreground = colors.fg,
    background = colors.bg,
    sp = colors.fg,
  },
  BufferLineDiagnosticVisible = { foreground = colors.fg, background = colors.bg, sp = colors.fg },

  BufferLineInfo = {
    foreground = colors.cyan,
    background = colors.bg,
    sp = colors.cyan,
    bold = true,
  },
  BufferLineInfoSelected = {
    foreground = colors.cyan,
    background = colors.bg,
    sp = colors.cyan,
    bold = true,
    italic = true,
  },
  BufferLineInfoVisible = {
    foreground = colors.cyan,
    background = colors.bg,
    sp = colors.cyan,
    bold = true,
  },
  BufferLineInfoDiagnostic = {
    foreground = colors.cyan,
    background = colors.bg,
    sp = colors.cyan,
  },
  BufferLineInfoDiagnosticSelected = {
    foreground = colors.cyan,
    background = colors.bg,
    sp = colors.cyan,
  },
  BufferLineInfoDiagnosticVisible = {
    foreground = colors.cyan,
    background = colors.bg,
    sp = colors.cyan,
  },
  BufferLineError = {
    foreground = colors.red,
    background = colors.bg,
    sp = colors.red,
    bold = true,
  },
  BufferLineErrorSelected = {
    foreground = colors.red,
    background = colors.bg,
    sp = colors.red,
    bold = true,
    italic = true,
  },
  BufferLineErrorVisible = {
    foreground = colors.red,
    background = colors.bg,
    sp = colors.red,
    bold = true,
  },
  BufferLineErrorDiagnostic = { foreground = colors.red, background = colors.bg, sp = colors.red },
  BufferLineErrorDiagnosticSelected = {
    foreground = colors.red,
    background = colors.bg,
    sp = colors.red,
  },
  BufferLineErrorDiagnosticVisible = {
    foreground = colors.red,
    background = colors.bg,
    sp = colors.red,
  },
  BufferLineWarning = {
    foreground = colors.yellow,
    background = colors.bg,
    sp = colors.yellow,
    bold = true,
    italic = true,
  },
  BufferLineWarningSelected = {
    foreground = colors.yellow,
    background = colors.bg,
    sp = colors.yellow,
    bold = true,
    italic = true,
  },
  BufferLineWarningVisible = {
    foreground = colors.yellow,
    background = colors.bg,
    sp = colors.yellow,
    bold = true,
  },
  BufferLineWarningDiagnostic = {
    foreground = colors.yellow,
    background = colors.bg,
    sp = colors.yellow,
  },
  BufferLineWarningDiagnosticSelected = {
    foreground = colors.yellow,
    background = colors.bg,
    sp = colors.yellow,
  },
  BufferLineWarningDiagnosticVisible = {
    foreground = colors.yellow,
    background = colors.bg,
    sp = colors.yellow,
  },

  PanelHeading = { background = colors.darker_black },
}
