require('indent_blankline').setup {
  indentLine_enabled = 1,
  char = '▏', -- ┆ ┊ 
  show_foldtext = false,
  show_current_context = false,
  show_current_context_start = false,
  filetype_exclude = {
    'help',
    'terminal',
    'dashboard',
    'packer',
    'lspinfo',
    'TelescopePrompt',
    'TelescopeResults',
    'log',
    'fugitive',
    'gitcommit',
    'packer',
    'vimwiki',
    'markdown',
    'txt',
    'vista',
    'NvimTree',
    'git',
    'undotree',
    'flutterToolsOutline',
    'norg',
    'org',
    'orgagenda',
    '', -- for all buffers without a file type
  },
  buftype_exclude = { 'terminal', 'nofile' },
  show_trailing_blankline_indent = false,
  show_first_indent_level = false,
  context_patterns = {
    'class',
    'function',
    'method',
    'block',
    'list_literal',
    'selector',
    '^if',
    '^table',
    'if_statement',
    'while',
    'for',
  },
}
